// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Solde de SOL d'un wallet (lu on-chain).
 */
export type Balance = { wallet: string, 
/**
 * Lamports, en chaîne.
 */
lamports: string, };
