// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProofJson } from "./ProofJson";
import type { ReplyTo } from "./ReplyTo";
import type { TradeParams } from "./TradeParams";

/**
 * Commande envoyée au moteur.
 */
export type Command = { "kind": "ping", id: string, reply: ReplyTo, 
/**
 * Horodatage de la demande (ms depuis l'epoch), en chaîne.
 */
requested_at_ms: string, } | { "kind": "create_wallet", id: string, reply: ReplyTo, user_id: string, seal_to: string, } | { "kind": "import_wallet", id: string, reply: ReplyTo, user_id: string, sealed: string, } | { "kind": "transport_key", id: string, reply: ReplyTo, } | { "kind": "new_nonce", id: string, reply: ReplyTo, user_id: string, } | { "kind": "register_passkey", id: string, reply: ReplyTo, user_id: string, credential_id: string, cose: string, seal_to: string, proof: ProofJson, } | { "kind": "verify_recovery", id: string, reply: ReplyTo, user_id: string, code: string, } | { "kind": "buy", id: string, reply: ReplyTo, user_id: string, 
/**
 * Wallet (base58) de l'utilisateur.
 */
wallet: string, 
/**
 * Mint du coin (base58).
 */
mint: string, 
/**
 * SOL à dépenser, en lamports (chaîne).
 */
sol_lamports: string, params: TradeParams, } | { "kind": "sell", id: string, reply: ReplyTo, user_id: string, wallet: string, mint: string, 
/**
 * Part à vendre, en points de base (10 000 = tout).
 */
percent_bps: number, params: TradeParams, } | { "kind": "positions", id: string, reply: ReplyTo, 
/**
 * Wallets (base58) de l'utilisateur.
 */
wallets: Array<string>, } | { "kind": "balances", id: string, reply: ReplyTo, wallets: Array<string>, } | { "kind": "reclaim_quote", id: string, reply: ReplyTo, wallets: Array<string>, } | { "kind": "withdraw", id: string, reply: ReplyTo, user_id: string, wallet: string, 
/**
 * Adresse de destination (base58).
 */
to: string, 
/**
 * Montant EXACT transféré, en lamports (chaîne). Les frais réseau s'y ajoutent.
 */
lamports: string, proof: ProofJson, } | { "kind": "group_changed", id: string, reply: ReplyTo, group_id: string, } | { "kind": "reclaim", id: string, reply: ReplyTo, user_id: string, wallet: string, } | { "kind": "totp_setup", id: string, reply: ReplyTo, user_id: string, seal_to: string, proof: ProofJson, } | { "kind": "totp_confirm", id: string, reply: ReplyTo, user_id: string, code: string, seal_to: string, } | { "kind": "verify_totp", id: string, reply: ReplyTo, user_id: string, code: string, } | { "kind": "regenerate_recovery", id: string, reply: ReplyTo, user_id: string, seal_to: string, proof: ProofJson, };
