// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Balance } from "./Balance";
import type { Position } from "./Position";
import type { ReclaimQuote } from "./ReclaimQuote";
import type { ReplyTo } from "./ReplyTo";

/**
 * Événement émis par le moteur.
 */
export type Event = { "kind": "auto_trade", id: string, reply: ReplyTo, 
/**
 * Nom du groupe.
 */
group: string, 
/**
 * Déclencheur : « snipe », « copy », « tp », « sl », « dev_sell », « timed ».
 */
action: string, 
/**
 * « buy » ou « sell ».
 */
side: string, mint: string, wallet: string, 
/**
 * « dry_run » (à blanc), « sent », « confirmed » ou « failed ».
 */
status: string, signature: string | null, 
/**
 * SOL engagé (achat) ou attendu (vente), en lamports.
 */
sol_lamports: string, 
/**
 * Fee Scope de la transaction, en lamports.
 */
fee_lamports: string, 
/**
 * Précision : raison d'un échec, palier de TP…
 */
detail: string | null, } | { "kind": "deposit", id: string, reply: ReplyTo, wallet: string, lamports: string, signature: string, } | { "kind": "pong", id: string, reply: ReplyTo, 
/**
 * Clé publique du signer (base58).
 */
signer_pubkey: string, 
/**
 * Signature du message de test (base58), vérifiée par le moteur.
 */
signature: string, 
/**
 * Temps d'aller-retour moteur → signer → moteur, en microsecondes.
 */
signer_roundtrip_us: number, } | { "kind": "wallet_created", id: string, reply: ReplyTo, 
/**
 * Adresse du wallet (base58).
 */
pubkey: string, 
/**
 * Clé privée scellée pour l'API (hex). Jamais en clair dans Redis.
 */
sealed: string, } | { "kind": "wallet_imported", id: string, reply: ReplyTo, pubkey: string, } | { "kind": "transport_key", id: string, reply: ReplyTo, 
/**
 * Clé publique X25519 du signer (hex).
 */
key: string, } | { "kind": "nonce", id: string, reply: ReplyTo, 
/**
 * Nonce à usage unique (hex).
 */
nonce: string, } | { "kind": "passkey_registered", id: string, reply: ReplyTo, 
/**
 * Codes de secours scellés pour l'API (hex), au tout premier facteur uniquement.
 */
recovery_sealed: string | null, } | { "kind": "recovery_codes", id: string, reply: ReplyTo, sealed: string, } | { "kind": "done", id: string, reply: ReplyTo, } | { "kind": "trade", id: string, reply: ReplyTo, 
/**
 * Signature de la transaction (base58), absente si rien n'a été envoyé.
 */
signature: string | null, status: string, 
/**
 * Raison de l'échec, le cas échéant.
 */
error: string | null, 
/**
 * SOL engagé (achat) ou attendu (vente), en lamports.
 */
sol_lamports: string, 
/**
 * Fee Scope prélevée, en lamports.
 */
fee_lamports: string, } | { "kind": "positions", id: string, reply: ReplyTo, positions: Array<Position>, } | { "kind": "balances", id: string, reply: ReplyTo, balances: Array<Balance>, } | { "kind": "reclaim_quotes", id: string, reply: ReplyTo, quotes: Array<ReclaimQuote>, } | { "kind": "reclaimed", id: string, reply: ReplyTo, signature: string | null, status: string, error: string | null, 
/**
 * SOL récupéré (dépôts + cashback), en lamports.
 */
lamports: string, } | { "kind": "totp_secret", id: string, reply: ReplyTo, sealed: string, } | { "kind": "withdrawn", id: string, reply: ReplyTo, signature: string | null, status: string, error: string | null, } | { "kind": "failed", id: string, reply: ReplyTo, reason: string, };
