// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tokens d'un coin détenus par un wallet (solde lu on-chain).
 */
export type Position = { wallet: string, mint: string, 
/**
 * Solde brut (en plus petites unités), en chaîne.
 */
amount: string, decimals: number, 
/**
 * Où il se trade : curve | pumpswap | other (pas un coin pump.fun : non vendable par Scope).
 */
venue: string, 
/**
 * Valeur estimée si tout est vendu maintenant (lamports, frais pump.fun déduits, estimation
 * prudente). Absente si le coin n'est pas vendable par Scope.
 */
value_lamports: string | null, };
