// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preuve d'une action sensible (voir `signer_frame::Proof`). Champs WebAuthn en base64url, tels que
 * renvoyés par le navigateur ; nonce en hex.
 */
export type ProofJson = { "type": "none" } | { "type": "passkey", nonce: string, credential_id: string, authenticator_data: string, client_data_json: string, signature: string, } | { "type": "recovery", code: string, } | { "type": "totp", code: string, };
