// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ce que la récupération rendrait pour un wallet.
 */
export type ReclaimQuote = { wallet: string, 
/**
 * Lamports récupérables (dépôts des compteurs + cashback), en chaîne.
 */
lamports: string, 
/**
 * Raison si la récupération est bloquée pour l'instant (récompenses à réclamer sur pump.fun).
 */
blocked: string | null, };
