// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * À qui renvoyer le résultat.
 */
export type ReplyTo = { "channel": "telegram", chat_id: string, } | { "channel": "web", session: string, } | { "channel": "api" } | { "channel": "user", user_id: string, };
