// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paramètres d'exécution communs à un trade.
 */
export type TradeParams = { 
/**
 * Tolérance de prix, en points de base (1 000 = 10 %).
 */
slippage_bps: number, 
/**
 * Prix de priorité (micro-lamports par unité de calcul), en chaîne ; « auto » = tarif réel du moment.
 */
priority_micro_lamports: string, 
/**
 * Tip Jito en lamports (« 0 » = aucun), en chaîne.
 */
tip_lamports: string, };
